os: osx
osx_image: xcode10.2
compiler:
  - clang
  - gcc
  - python

addons:
  homebrew:
    packages:
    - cmake
    - conan
    - nasm
    - llvm@6
    - qemu

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - script:
        - mkdir build_hello_world && cd build_hello_world
        - conan install .. -pr clang-6.0-macos-x86_64
        - source activate.sh
        - cmake -DFOR_PRODUCTION=OFF ..
        - cmake --build .
        - gtimeout 7 boot hello &> hello_log.txt || true
        - |
          if grep -F "Running [ Hello world - OS included ]" hello_log.txt
          then
            echo "Hello World -  Success! :)"
          else
            echo "Failed :("
            cat -b hello_log.txt
            exit 1
          fi
      name: "clang-6.0-x86_64"

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version
  - clang --version
  - pip3 install future
  - pip3 install --upgrade psutil
  - pip3 install --upgrade jsonschema

after_script:
  - source deactivate.sh
